# Generated by Django 3.1.13 on 2021-09-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='minecraft_uuid',
            field=models.CharField(default='not set', max_length=36),
        ),
    ]
