# Generated by Django 3.1.13 on 2021-09-11 02:32

import accounts.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=accounts.models.get_default_amount, size=5),
        ),
    ]
