# Generated by Django 3.1.13 on 2021-09-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='succeeded',
            field=models.BooleanField(default=True),
        ),
    ]
