# Generated by Django 3.1.13 on 2021-09-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210909_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='New Account', max_length=32),
        ),
    ]
