# Generated by Django 3.1.13 on 2021-09-15 18:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=16, unique=True, validators=[accounts.models.validate_username], verbose_name='Minecraft Username'),
        ),
    ]
