# Generated by Django 3.1.13 on 2021-09-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210920_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('owner', '-primary')},
        ),
        migrations.CreateModel(
            name='DepositWithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal')], default='D', max_length=1)),
                ('netherite_blocks', models.PositiveIntegerField(default=0)),
                ('netherite_ingots', models.PositiveIntegerField(default=0)),
                ('netherite_scrap', models.PositiveIntegerField(default=0)),
                ('diamond_blocks', models.PositiveIntegerField(default=0)),
                ('diamonds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('R', 'Rejected')], default='P', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ('status',),
            },
        ),
    ]
