# Generated by Django 3.1.13 on 2021-09-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210922_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositwithdrawalrequest',
            options={'ordering': ('status', 'date_created')},
        ),
    ]
