# Generated by Django 3.1.13 on 2021-09-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210927_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositwithdrawalrequest',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='depositwithdrawalrequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='accounts.account'),
        ),
    ]
