# Generated by Django 3.1.13 on 2021-09-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ('-date',)},
        ),
    ]
