# Generated by Django 3.1.13 on 2021-09-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_auto_20210928_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ('date',)},
        ),
    ]
